### ISSUE TITLE
Failed to retrieve access token

### ISSUE THREAD

**Issue by srmagura** [zerosecrets/cli#11]
`zero-cli auth login`  returns an error upon submitting a valid code.

![auth-failure](https://github.com/zerosecrets/cli/assets/801549/96d026ed-89c5-486e-be93-9abb267eb239)

**Comment by srmagura** [comment]
moved to Linear

**Comment by sarvesh4396** [comment]
Any Update on this as this is broken and doesnt allow to use cli.

Also url https://app.tryzero.com/cli-success-login is broken it should be https://tryzero.com/cli-success-login
